// Generated by LiveScript 1.3.1
var lson;
lson = require("lson");
module.exports = function(source){
  if (typeof this.cacheable == 'function') {
    this.cacheable();
  }
  return this.callback(null, "(function(){\n    module.exports = " + lson.stringify(lson.parse(source)).replace(/\\?[\"\']/g, "\"") + ";\n    return module.exports;\n})();");
};